# Generated by Django 6.0 on 2025-12-20 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment_date",
                    models.DateField(
                        db_index=True,
                        help_text="The date the payment was made",
                        verbose_name="Payment Date",
                    ),
                ),
                (
                    "payment_value",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        help_text="The value of the payment",
                        max_digits=12,
                        verbose_name="Payment Value",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        help_text="The loan that the payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="loans.loan",
                        verbose_name="Loan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["loan", "-payment_date"], name="payment_loan_date_idx"
                    ),
                    models.Index(
                        fields=["loan", "-created_at"], name="payment_loan_created_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("payment_value__gt", 0)),
                        name="payment_value_positive",
                    )
                ],
            },
        ),
    ]
