# Generated by Django 6.0 on 2025-12-20 13:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.CharField(
                        db_index=True,
                        help_text="The bank that lent the money",
                        max_length=255,
                        verbose_name="Bank",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of money borrowed",
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly interest rate in percentage (e.g., 2.5 for 2.5%)",
                        max_digits=10,
                        verbose_name="Interest Rate",
                    ),
                ),
                (
                    "request_date",
                    models.DateField(
                        db_index=True,
                        help_text="The date the loan was requested",
                        verbose_name="Request Date",
                    ),
                ),
                ("request_ip", models.GenericIPAddressField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The user who owns the loan",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
                "ordering": ["-request_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-request_date"], name="loan_owner_date_idx"
                    ),
                    models.Index(
                        fields=["owner", "-created_at"], name="loan_owner_created_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="loan_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("interest_rate__gte", 0), ("interest_rate__lte", 100)
                        ),
                        name="loan_interest_rate_range",
                    ),
                ],
            },
        ),
    ]
